package js.java.schaltungen.chatcomng;

public enum BOTCOMMAND {
   ALIVE(".ALIVE"),
   LEAVING(".LEAVING"),
   UPDATE(".UPDATE"),
   NORUPDATE(".NORUPDATE"),
   RESERVE(".RESERVE"),
   RESERVERESPONSE(".RESERVERESPONSE"),
   TRAIN(".TRAIN"),
   TRAINRESPONSE(".TRAINRESPONSE"),
   TRAINBLOCK(".TRAINBLOCK"),
   FAHRPLAN(".FAHRPLAN"),
   FATCODECHECK(".FATCODECHECK"),
   ZREDIRECTREQ(".ZREDIRECTREQ"),
   ZREQUESTFPL(".ZREQUESTFPL"),
   ZREDIRECTWAY(".ZREDIRECTWAY"),
   ZREDIRECTACK(".ZREDIRECTACK"),
   QSCOMMENT(".QSCOMMENT"),
   ENTERSIGNAL(".ENTERSIGNAL"),
   HOSTINFO(".HOSTINFO"),
   CCODE(".CCODE"),
   UCODE(".UCODE");

   public final String command;

   private BOTCOMMAND(String cmd) {
      this.command = cmd;
   }
}
