name: Update Source
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */7 * *"

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Source
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: ./update.main.kts
      - name: Capture STS Build Number
        id: build
        run: echo "STS_BUILD=$(cat ./sts/src/main/resources/js/java/build/build.property | awk -F '=' '/^[^#]/ {print $2}')" >> $GITHUB_OUTPUT
      - name: Create/Update PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: update StellwerkSim Source (Build ${{ steps.build.outputs.STS_BUILD }}"
          branch: sts-update
          title: Update StellwerkSim to Build ${{ steps.build.outputs.STS_BUILD }}
          labels: sts-updates
          reviewers: nycodeghg
          committer: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
